name: Build and Deoploy Github Pages

on: [push, pull_request ]
permissions:
  id-token: read

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: actions/jekyll-build-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}