name: Build and Deoploy Github Pages

on: [push, pull_request ]

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./src
    - name: Deploy
      uses: actions/deploy-pages@v1